version: '3.9'

services:
  postgres:
    container_name: postgres_lab_java
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lab_java
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - postgres
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer_lab_java
    image: adminer
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres
    ports:
      - 8080:8080

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
